name: Mirroring

on:
  push:
    branches:
      - master

jobs:
  to_codecommit:                                        # <-- different jobs are executed in parallel.
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          ssh://git-codecommit.us-west-2.amazonaws.com/v1/repos/modzel-mirror-test
        ssh_private_key:
          ${{ secrets.CODECOMMIT_SSH_PRIVATE_KEY }}
        ssh_username:                                   # <-- (for codecommit) you need to specify ssh-key-id as ssh username.
          ${{ secrets.CODECOMMIT_SSH_PRIVATE_KEY_ID }}
    - uses: actions/hello-world-javascript-action@master
      with:
        who-to-greet: 'your mama'